{
  imports = [
    ./ale
    ./editorconfig-vim
    ./fugitive
    ./gitsigns
    ./hop
    ./leap-nvim
    ./lightline-vim
    ./monokai
    ./nerdcommenter
    ./nvim-hlslens
    ./nvim-surround
    ./repeat
    ./supertab
    ./telescope
    ./treesitter
    ./vim-easy-align
    ./vim-eunuch
    ./vim-filebeagle
    ./vim-grepper
    ./vim-plugin-ruscmd
    ./_filetypes
    ./_experimental
    ./_base
  ];
}
